name: Terraform configmanagement
run-name: Deploy by @${{ github.actor }} 

on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - env:
          AWS_ACCESS_KEY_ID: ${{AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{REGION}}
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform plan

  deploy:
    if: ${{ github.event_name == 'push' }} # only run for PRs
    runs-on: ubuntu-latest
    steps:
      - env:
          AWS_ACCESS_KEY_ID: ${{AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{REGION}}
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform apply -auto-approve
