name: Terraform config management
run-name: Deploy by @${{ github.actor }} 

on:
  pull_request: {}
  push:
    branches: 
    - main
    - dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  plan:
    if: ${{ github.event_name == 'pull_request' }} # only run for PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform workspace select prod
      - run: terraform plan

  Dev_deploy:
    if: ${{ github.event_name == 'push' }} && ${{ GITHUB_REF == 'refs/heads/dev' }} # only run for PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform workspace select prod
      - run: terraform plan
      - run: terraform apply -auto-approve
  
  Prod_deploy:
    if: ${{ github.event_name == 'push' }} && ${{ GITHUB_REF == 'refs/heads/main' }} # only run for PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform workspace select prod
      - run: terraform plan
      - run: terraform apply -auto-approve
